# Generated by Django 5.0.3 on 2024-04-04 19:18

import django.core.validators
import django.db.models.deletion
import register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='N/A', max_length=25)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('longtitude', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=120)),
                ('uemail', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(), register.models.validate_email])),
                ('ucontact', models.CharField(max_length=15)),
                ('upwd', models.CharField(max_length=10)),
                ('ulocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.location')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
