# Generated by Django 5.0.3 on 2024-04-20 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('subcat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcatCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcat.subcat')),
            ],
            options={
                'db_table': 'subcat_counts',
            },
        ),
    ]
