# Generated by Django 5.0.3 on 2024-04-20 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_subcatcount'),
        ('subcat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcatcount',
            name='subcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcat.subcat', unique=True),
        ),
    ]
